-- Insert ZONE Table Data
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (1,1,'LbPlo','Labial Plosives','p');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (1,2,'ApPlo','Apical Plosives','t');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (1,3,'LmPlo','Laminal Plosives','tS');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (1,4,'DoPlo','Dorsal Plosives','k');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (1,5,'PDPlo','Postdorsal Plosives','?');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (2,1,'LbNas','Labial Nasals','m');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (2,2,'ApNas','Apical Nasals','n');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (2,3,'LmNas','Laminal Nasals','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (2,4,'DoNas','Dorsal Nasals','N');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (2,5,'PDNas','Postdorsal Nasals','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (3,1,'LbRes','Labial Resonants','b~');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (3,2,'ApRes','Apical Resonants','r');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (3,3,'LmRes','Laminal Resonants','l~');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (3,4,'DoRes','Dorsal Resonants','L');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (3,5,'PDRes','Postdorsal Resonants','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (4,1,'LbFri','Labial Fricatives','P');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (4,2,'ApFri','Apical Fricatives','s');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (4,3,'LmFri','Laminal Fricatives','S');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (4,4,'DoFri','Dorsal Fricatives','X');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (4,5,'PDFri','Postdorsal Fricatives','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (5,1,'LbApp','Labial Approximants','w');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (5,2,'ApApp','Apical Approximants','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (5,3,'LmApp','Laminal Approximants','y');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (5,4,'DoApp','Dorsal Approximants','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (5,5,'PDApp','Postdorsal Approximants','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (6,2,'ClFr','Close Front','I');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (6,3,'ClCn','Close Central','+');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (6,4,'ClBk','Close Back','u');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (7,2,'ClMidFr','Close-Mid Front','e');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (7,3,'ClMidCn','Close-Mid Central','^');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (7,4,'ClMidBk','Close-Mid Back','o');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (8,2,'OpMidFr','Open-Mid Front','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (8,3,'OpMidCn','Open-Mid Central','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (8,4,'OpMidBk','Open-Mid Back','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (9,2,'OpFr','Open Front','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (9,3,'OpCn','Open Central','a');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (9,4,'OpBk','Open Back','');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (10,1,'Proc','Process','ep');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (10,3,'Pros','Prosody','`');
insert into ZONE (ZONE_ROW,ZONE_COL,ZONE_ABBR,ZONE_NAME,ZONE_TYPE) values (10,5,'RES','RESIDUE','-');